export type CategoryGroup = {
  name: string;
  slug: string;
  children: {
    name: string;
    slug: string;
  }[];
};

export const CATEGORY_TREE: CategoryGroup[] = [
  {
    name: "Food & Drink",
    slug: "food-drink",
    children: [
      { name: "Restaurant", slug: "restaurant" },
      { name: "Coffee Shop", slug: "coffee-shop" },
      { name: "Bakery", slug: "bakery" },
      { name: "Bar", slug: "bar" },
      { name: "Brewery", slug: "brewery" },
      { name: "Wine Bar", slug: "wine-bar" },
      { name: "Dessert Shop", slug: "dessert-shop" },
      { name: "Ice Cream Shop", slug: "ice-cream-shop" },
      { name: "Food Truck", slug: "food-truck" },
      { name: "Juice Bar", slug: "juice-bar" },
      { name: "Deli", slug: "deli" },
      { name: "Pizza", slug: "pizza" },
      { name: "Seafood", slug: "seafood" },
      { name: "Steakhouse", slug: "steakhouse" },
      { name: "Sushi", slug: "sushi" },
      { name: "Mexican", slug: "mexican" },
      { name: "Italian", slug: "italian" },
      { name: "BBQ", slug: "bbq" },
      { name: "Breakfast & Brunch", slug: "breakfast-brunch" },
      { name: "Fruit Stand", slug: "fruit-stand" },
      { name: "Other", slug: "other-food-drink" },
    ],
  },
  {
    name: "Shopping",
    slug: "shopping",
    children: [
      { name: "Clothing Store", slug: "clothing-store" },
      { name: "Bookstore", slug: "bookstore" },
      { name: "Gift Shop", slug: "gift-shop" },
      { name: "Jewelry Store", slug: "jewelry-store" },
      { name: "Florist", slug: "florist" },
      { name: "Furniture Store", slug: "furniture-store" },
      { name: "Home Decor", slug: "home-decor" },
      { name: "Electronics Store", slug: "electronics-store" },
      { name: "Pet Store", slug: "pet-store" },
      { name: "Toy Store", slug: "toy-store" },
      { name: "Thrift Store", slug: "thrift-store" },
      { name: "Grocery Store", slug: "grocery-store" },
      { name: "Farmers Market Vendor", slug: "farmers-market-vendor" },
      { name: "Other", slug: "other-shopping" },
    ],
  },
  {
    name: "Health & Beauty",
    slug: "health-beauty",
    children: [
      { name: "Salon", slug: "salon" },
      { name: "Barber Shop", slug: "barber-shop" },
      { name: "Spa", slug: "spa" },
      { name: "Massage", slug: "massage" },
      { name: "Nail Salon", slug: "nail-salon" },
      { name: "Gym", slug: "gym" },
      { name: "Yoga Studio", slug: "yoga-studio" },
      { name: "Pilates Studio", slug: "pilates-studio" },
      { name: "Personal Trainer", slug: "personal-trainer" },
      { name: "Skincare", slug: "skincare" },
      { name: "Tattoo Shop", slug: "tattoo-shop" },
      { name: "Other", slug: "other-health-beauty" },
    ],
  },
  {
    name: "Home & Auto",
    slug: "home-auto",
    children: [
      { name: "Auto Repair", slug: "auto-repair" },
      { name: "Car Wash", slug: "car-wash" },
      { name: "Detailing", slug: "detailing" },
      { name: "Plumber", slug: "plumber" },
      { name: "Electrician", slug: "electrician" },
      { name: "HVAC", slug: "hvac" },
      { name: "Landscaping", slug: "landscaping" },
      { name: "Cleaning Service", slug: "cleaning-service" },
      { name: "Handyman", slug: "handyman" },
      { name: "Roofing", slug: "roofing" },
      { name: "Moving Company", slug: "moving-company" },
      { name: "Pest Control", slug: "pest-control" },
      { name: "Other", slug: "other-home-auto" },
    ],
  },
  {
    name: "Professional Services",
    slug: "professional-services",
    children: [
      { name: "Law Firm", slug: "law-firm" },
      { name: "Accounting", slug: "accounting" },
      { name: "Insurance Agency", slug: "insurance-agency" },
      { name: "Real Estate", slug: "real-estate" },
      { name: "Marketing Agency", slug: "marketing-agency" },
      { name: "Web Design", slug: "web-design" },
      { name: "Photography", slug: "photography" },
      { name: "Printing", slug: "printing" },
      { name: "Consulting", slug: "consulting" },
      { name: "Event Planning", slug: "event-planning" },
      { name: "Other", slug: "other-professional-services" },
    ],
  },
  {
    name: "Entertainment & Recreation",
    slug: "entertainment-recreation",
    children: [
      { name: "Movie Theater", slug: "movie-theater" },
      { name: "Bowling Alley", slug: "bowling-alley" },
      { name: "Arcade", slug: "arcade" },
      { name: "Music Venue", slug: "music-venue" },
      { name: "Museum", slug: "museum" },
      { name: "Art Gallery", slug: "art-gallery" },
      { name: "Park", slug: "park" },
      { name: "Escape Room", slug: "escape-room" },
      { name: "Mini Golf", slug: "mini-golf" },
      { name: "Dance Studio", slug: "dance-studio" },
      { name: "Other", slug: "other-entertainment-recreation" },
    ],
  },
];