INSERT INTO categories (id, name, slug, parent_slug) VALUES
-- Main categories
(gen_random_uuid(), 'Food & Drink', 'food-drink', NULL),
(gen_random_uuid(), 'Shopping', 'shopping', NULL),
(gen_random_uuid(), 'Health & Beauty', 'health-beauty', NULL),
(gen_random_uuid(), 'Home & Auto', 'home-auto', NULL),
(gen_random_uuid(), 'Professional Services', 'professional-services', NULL),
(gen_random_uuid(), 'Entertainment & Recreation', 'entertainment-recreation', NULL),
(gen_random_uuid(), 'Other', 'other', NULL),

-- Food & Drink
(gen_random_uuid(), 'Restaurant', 'restaurant', 'food-drink'),
(gen_random_uuid(), 'Coffee Shop', 'coffee-shop', 'food-drink'),
(gen_random_uuid(), 'Bakery', 'bakery', 'food-drink'),
(gen_random_uuid(), 'Bar', 'bar', 'food-drink'),
(gen_random_uuid(), 'Brewery', 'brewery', 'food-drink'),
(gen_random_uuid(), 'Wine Bar', 'wine-bar', 'food-drink'),
(gen_random_uuid(), 'Dessert Shop', 'dessert-shop', 'food-drink'),
(gen_random_uuid(), 'Ice Cream Shop', 'ice-cream-shop', 'food-drink'),
(gen_random_uuid(), 'Food Truck', 'food-truck', 'food-drink'),
(gen_random_uuid(), 'Juice Bar', 'juice-bar', 'food-drink'),
(gen_random_uuid(), 'Deli', 'deli', 'food-drink'),
(gen_random_uuid(), 'Pizza', 'pizza', 'food-drink'),
(gen_random_uuid(), 'Seafood', 'seafood', 'food-drink'),
(gen_random_uuid(), 'Steakhouse', 'steakhouse', 'food-drink'),
(gen_random_uuid(), 'Sushi', 'sushi', 'food-drink'),
(gen_random_uuid(), 'Mexican', 'mexican', 'food-drink'),
(gen_random_uuid(), 'Italian', 'italian', 'food-drink'),
(gen_random_uuid(), 'BBQ', 'bbq', 'food-drink'),
(gen_random_uuid(), 'Breakfast & Brunch', 'breakfast-brunch', 'food-drink'),
(gen_random_uuid(), 'Fruit Stand', 'fruit-stand', 'food-drink'),
(gen_random_uuid(), 'Other Food & Drink', 'other-food-drink', 'food-drink'),

-- Shopping
(gen_random_uuid(), 'Clothing Store', 'clothing-store', 'shopping'),
(gen_random_uuid(), 'Bookstore', 'bookstore', 'shopping'),
(gen_random_uuid(), 'Gift Shop', 'gift-shop', 'shopping'),
(gen_random_uuid(), 'Jewelry Store', 'jewelry-store', 'shopping'),
(gen_random_uuid(), 'Florist', 'florist', 'shopping'),
(gen_random_uuid(), 'Furniture Store', 'furniture-store', 'shopping'),
(gen_random_uuid(), 'Home Decor', 'home-decor', 'shopping'),
(gen_random_uuid(), 'Electronics Store', 'electronics-store', 'shopping'),
(gen_random_uuid(), 'Pet Store', 'pet-store', 'shopping'),
(gen_random_uuid(), 'Toy Store', 'toy-store', 'shopping'),
(gen_random_uuid(), 'Thrift Store', 'thrift-store', 'shopping'),
(gen_random_uuid(), 'Grocery Store', 'grocery-store', 'shopping'),
(gen_random_uuid(), 'Farmers Market Vendor', 'farmers-market-vendor', 'shopping'),
(gen_random_uuid(), 'Other Shopping', 'other-shopping', 'shopping'),

-- Health & Beauty
(gen_random_uuid(), 'Salon', 'salon', 'health-beauty'),
(gen_random_uuid(), 'Barber Shop', 'barber-shop', 'health-beauty'),
(gen_random_uuid(), 'Spa', 'spa', 'health-beauty'),
(gen_random_uuid(), 'Massage', 'massage', 'health-beauty'),
(gen_random_uuid(), 'Nail Salon', 'nail-salon', 'health-beauty'),
(gen_random_uuid(), 'Gym', 'gym', 'health-beauty'),
(gen_random_uuid(), 'Yoga Studio', 'yoga-studio', 'health-beauty'),
(gen_random_uuid(), 'Pilates Studio', 'pilates-studio', 'health-beauty'),
(gen_random_uuid(), 'Personal Trainer', 'personal-trainer', 'health-beauty'),
(gen_random_uuid(), 'Skincare', 'skincare', 'health-beauty'),
(gen_random_uuid(), 'Tattoo Shop', 'tattoo-shop', 'health-beauty'),
(gen_random_uuid(), 'Other Health & Beauty', 'other-health-beauty', 'health-beauty'),

-- Home & Auto
(gen_random_uuid(), 'Auto Repair', 'auto-repair', 'home-auto'),
(gen_random_uuid(), 'Car Wash', 'car-wash', 'home-auto'),
(gen_random_uuid(), 'Detailing', 'detailing', 'home-auto'),
(gen_random_uuid(), 'Plumber', 'plumber', 'home-auto'),
(gen_random_uuid(), 'Electrician', 'electrician', 'home-auto'),
(gen_random_uuid(), 'HVAC', 'hvac', 'home-auto'),
(gen_random_uuid(), 'Landscaping', 'landscaping', 'home-auto'),
(gen_random_uuid(), 'Cleaning Service', 'cleaning-service', 'home-auto'),
(gen_random_uuid(), 'Handyman', 'handyman', 'home-auto'),
(gen_random_uuid(), 'Roofing', 'roofing', 'home-auto'),
(gen_random_uuid(), 'Moving Company', 'moving-company', 'home-auto'),
(gen_random_uuid(), 'Pest Control', 'pest-control', 'home-auto'),
(gen_random_uuid(), 'Other Home & Auto', 'other-home-auto', 'home-auto'),

-- Professional Services
(gen_random_uuid(), 'Law Firm', 'law-firm', 'professional-services'),
(gen_random_uuid(), 'Accounting', 'accounting', 'professional-services'),
(gen_random_uuid(), 'Insurance Agency', 'insurance-agency', 'professional-services'),
(gen_random_uuid(), 'Real Estate', 'real-estate', 'professional-services'),
(gen_random_uuid(), 'Marketing Agency', 'marketing-agency', 'professional-services'),
(gen_random_uuid(), 'Web Design', 'web-design', 'professional-services'),
(gen_random_uuid(), 'Photography', 'photography', 'professional-services'),
(gen_random_uuid(), 'Printing', 'printing', 'professional-services'),
(gen_random_uuid(), 'Consulting', 'consulting', 'professional-services'),
(gen_random_uuid(), 'Event Planning', 'event-planning', 'professional-services'),
(gen_random_uuid(), 'Other Professional Services', 'other-professional-services', 'professional-services'),

-- Entertainment & Recreation
(gen_random_uuid(), 'Movie Theater', 'movie-theater', 'entertainment-recreation'),
(gen_random_uuid(), 'Bowling Alley', 'bowling-alley', 'entertainment-recreation'),
(gen_random_uuid(), 'Arcade', 'arcade', 'entertainment-recreation'),
(gen_random_uuid(), 'Music Venue', 'music-venue', 'entertainment-recreation'),
(gen_random_uuid(), 'Museum', 'museum', 'entertainment-recreation'),
(gen_random_uuid(), 'Art Gallery', 'art-gallery', 'entertainment-recreation'),
(gen_random_uuid(), 'Park', 'park', 'entertainment-recreation'),
(gen_random_uuid(), 'Escape Room', 'escape-room', 'entertainment-recreation'),
(gen_random_uuid(), 'Mini Golf', 'mini-golf', 'entertainment-recreation'),
(gen_random_uuid(), 'Dance Studio', 'dance-studio', 'entertainment-recreation'),
(gen_random_uuid(), 'Other Entertainment & Recreation', 'other-entertainment-recreation', 'entertainment-recreation')
ON CONFLICT (slug) DO NOTHING;